### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading '0') at 22:11

### ISSUE THREAD

**Issue by pstaszko** [puppetmaster-/vampire_survivors_mods#3]
This is the second time my game crashed on this level. I think the last time was about 20 minutes in or something too. I attached my modified js file.
[Window Title]
VampireSurvivors.exe

[Content]
Uncaught TypeError: Cannot read properties of undefined (reading '0')
 ------ 
TypeError
Cannot read properties of undefined (reading '0')
TypeError: Cannot read properties of undefined (reading '0')
    at _0x4bd195.Init (file:///:192:590)
    at _0x3cd4d5.Spawn (file:///C:/Users/Paul/scoop/persist/steam/steamapps/common/Vampire%20Survivors/resources/app/.webpack/renderer/main.bundle.js:873:539)
    at _0x3cd4d5.SpawnAt (file:///C:/Users/Paul/scoop/persist/steam/steamapps/common/Vampire%20Survivors/resources/app/.webpack/renderer/main.bundle.js:873:186)
    at _0x302675._spawnOneInRandomLocationHorizontal (file:///C:/Users/Paul/scoop/persist/steam/steamapps/common/Vampire%20Survivors/resources/app/.webpack/renderer/main.bundle.js:2098:813)
    at _0x302675.SpawnInRandomLocationH (file:///C:/Users/Paul/scoop/persist/steam/steamapps/common/Vampire%20Survivors/resources/app/.webpack/renderer/main.bundle.js:2101:360)
    at Function.callback (file:///C:/Users/Paul/scoop/persist/steam/steamapps/common/Vampire%20Survivors/resources/app/.webpack/renderer/main.bundle.js:2087:357)
    at initialize.update (file:///C:/Users/Paul/scoop/persist/steam/steamapps/common/Vampire%20Survivors/resources/app/.webpack/renderer/vendors.bundle.js:2:1367335)
    at initialize.l.emit (file:///C:/Users/Paul/scoop/persist/steam/steamapps/common/Vampire%20Survivors/resources/app/.webpack/renderer/vendors.bundle.js:2:358264)
    at initialize.step (file:///C:/Users/Paul/scoop/persist/steam/steamapps/common/Vampire%20Survivors/resources/app/.webpack/renderer/vendors.bundle.js:2:575854)
    at initialize.update (file:///C:/Users/Paul/scoop/persist/steam/steamapps/common/Vampire%20Survivors/resources/app/.webpack/renderer/vendors.bundle.js:2:842047)

[OK
[main.bundle.js.txt](https://github.com/puppetmaster-/vampire_survivors_mods/files/8500450/main.bundle.js.txt)
]

**Comment by pstaszko** [comment]
![image](https://user-images.githubusercontent.com/14144789/163699576-1efe8096-fb62-4fcc-be5d-28e756a0d879.png)
I took another shot at it. Different character and no speedwalking powerups. I thought something near the erroring out code had to do with speed so I avoided the upgrade this time. I had it the first time. Hope it helps! I look forward to beating this map, it's very challenging! Thanks :)

**Comment by puppetmaster-** [comment]
thanks for reporting, it looks like 'ARMORSPEAR' is no longer a valid opponent.

Please replace 'ARMORSPEAR' with 'ARMORSPEAR_6'.

I'm testing if there are more changes to the opponent names.

**Comment by puppetmaster-** [comment]
and also 'ARMOR' must be replaced with 'ARMOR_6', but be careful not to overwrite the item name.

**Comment by puppetmaster-** [comment]
fixed in [change enemy spawn name for armor](https://github.com/puppetmaster-/vampire_survivors_mods/commit/0e3379dfb69faca79f6eb8093bf54994bd3f1462)
and [change enemy spawn name](https://github.com/puppetmaster-/vampire_survivors_mods/commit/f706830293a363620d89cd1a9396c28d1753dc6e)
